### ISSUE TITLE
期待更新部署说明

### ISSUE THREAD

**Issue by cohux** [xuchaoa/CTF_AWD_Platform#15]
期待更新部署说明

**Comment by xuchaoa** [comment]
最近在准备了考试，可能开发进度要慢一些了，demo基本功能都实现了，还有一些小问题比如用户交互、前端友好等一下小问题需要完善

**Comment by cohux** [comment]
能不能把部署文档提交一份，对您这个项目很感兴趣，但是环境跑不起来
